"""empty message

Revision ID: 1aeba357a6d0
Revises: 
Create Date: 2023-03-21 14:11:35.508540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aeba357a6d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Parent',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('School',
    sa.Column('name', sa.Text(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.Text(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(length=100), nullable=False),
    sa.Column('bdate', sa.Text(length=10), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['School.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ParentStudent',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['Parent.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ParentStudent')
    op.drop_table('Student')
    op.drop_table('School')
    op.drop_table('Parent')
    # ### end Alembic commands ###
