"""empty message

Revision ID: 604416b89e77
Revises: 1aeba357a6d0
Create Date: 2023-03-21 14:14:04.427683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604416b89e77'
down_revision = '1aeba357a6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Parent', sa.Column('phone', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Parent', 'phone')
    # ### end Alembic commands ###
